version: "3.3"

services:
  mongo:
    image: mongo:${MONGO_VERSION}
    restart: always
    ports:
      - "27017:27017"
    networks:
      dev-network:
        aliases:
          - mongo.dev
    volumes:
      - "mongo_data:/data/db"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      dev-network:
        aliases:
          - elasticsearch.dev
    volumes:
      - "es_data:/usr/share/elasticsearch/data"

volumes:
  mongo_data:
  es_data:

networks:
  dev-network:
